version: '2'
services:
  elasticsearch-1:
    image: elasticsearch:1
    hostname: elasticsearch-1
    container_name: elasticsearch-1
    command: "elasticsearch -Des.cluster.name=docker-es-1 -Dnetwork.bind_host=0.0.0.0"
    restart: unless-stopped
    network_mode: "host"
    environment:
    - ES_HEAP_SIZE=2g
    ports:
    - "9200:9200"
    - "9300:9300"
  
  elasticsearch-2:
    image: elasticsearch:2
    hostname: elasticsearch-2
    container_name: elasticsearch-2
    command: "elasticsearch -Des.cluster.name=docker-es-2 -Dnetwork.bind_host=0.0.0.0"
    restart: unless-stopped
    environment:
    - ES_HEAP_SIZE=2g
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
      - network
    
  elasticsearch-5:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    hostname: elasticsearch5
    container_name: elasticsearch5
    environment:
      - xpack.security.enabled=false
      - cluster.name=docker-es-5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - network

  kibana-5:
    image: docker.elastic.co/kibana/kibana:5.3.0
    container_name: kibana5
    environment:
      ELASTICSEARCH_URL: http://elasticsearch5:9200
    ports:
      - 5601:5601
    networks:
      - network

# Have Bind Mounts on the docker engine
volumes:
  esdata1:
    driver: local

networks:
  network:
    driver: bridge
